/** Single source for Admin tab labels — keep emojis consistent everywhere. */
export const ADMIN_CMS_TABS = [
  { id: 'overview', label: '📋 Overview' },
  { id: 'settings', label: '⚙️ Site copy' },
  { id: 'games', label: '🎮 Games' },
  { id: 'pages', label: '📄 Pages' },
  { id: 'nav', label: '🧭 Navigation' },
  { id: 'devlogs', label: '📝 Dev logs' },
] as const;

export const ADMIN_STUDIO_TABS = [
  { id: 'theme', label: '🎨 Theme' },
  { id: 'effects', label: '⚡ Effects' },
  { id: 'typography', label: '🔤 Typography' },
  { id: 'layout', label: '📐 Layout' },
  { id: 'components', label: '🧩 Components' },
  { id: 'behavior', label: '🎛 Behavior' },
  { id: 'seo', label: '🔍 SEO + Head' },
  { id: 'brand', label: '🪪 Brand + Hero' },
  { id: 'social', label: '🌐 Social' },
  { id: 'motion', label: '🎬 Motion' },
  { id: 'media', label: '🎵 Audio + FX' },
  { id: 'system', label: '♿ System' },
  { id: 'homepage', label: '🏠 Homepage' },
  { id: 'analytics', label: '📊 Analytics' },
  { id: 'mailing', label: '✉️ Mailing' },
] as const;

export const ADMIN_OVERVIEW_CARDS: { id: string; title: string; desc: string }[] = [
  { id: 'settings', title: '⚙️ Site copy', desc: 'Hero text, support block, promos, footer — not global FX (see Effects).' },
  { id: 'games', title: '🎮 Games', desc: 'ZIP uploads, itch links, per-game 🎨 appearance + blocks.' },
  { id: 'pages', title: '📄 Pages & panels', desc: 'Custom URLs, HTML apps, per-page 🎨 appearance + blocks.' },
  {
    id: 'nav',
    title: '🧭 Navigation',
    desc: 'Extra top-bar links after Home / Vault / Dev log (Discord, press kit, …).',
  },
  { id: 'devlogs', title: '📝 Dev logs', desc: 'News and build notes.' },
  { id: 'theme', title: '🎨 Theme Studio', desc: 'Colours, gradients, background image/video.' },
  { id: 'effects', title: '⚡ Effects Studio', desc: 'Scanlines, grain, moods, card FX — one place for all layers.' },
  { id: 'typography', title: '🔤 Typography', desc: 'Google Fonts, sizes, hero shadow, links.' },
  { id: 'layout', title: '📐 Layout', desc: 'Container width, grid, nav/footer alignment.' },
  { id: 'components', title: '🧩 Components', desc: 'Cards, buttons, panels, modals.' },
  { id: 'behavior', title: '🎛 Behavior', desc: 'Nav flags, maintenance, filters, card hover style.' },
  { id: 'seo', title: '🔍 SEO + Head', desc: 'Meta, OG, favicon, analytics script.' },
  { id: 'brand', title: '🪪 Brand + Hero', desc: 'Logo, tagline, hero CTAs, watermark.' },
  { id: 'social', title: '🌐 Social + Sharing', desc: 'Follow icons + share strips.' },
  { id: 'motion', title: '🎬 Motion + Cards', desc: 'Page entrance, route fade, promo motion.' },
  { id: 'media', title: '🎵 Audio + Cursor', desc: 'BGM, hover sounds, cursor, particles.' },
  { id: 'system', title: '♿ Performance + A11y', desc: 'Reduce motion, contrast, focus ring.' },
  { id: 'homepage', title: '🏠 Homepage builder', desc: 'Hero, galleries, columns, tabs, FAQs — any block.' },
  {
    id: 'analytics',
    title: '📊 Analytics',
    desc: 'Traffic, plays, sign-ins (migration 020).',
  },
  {
    id: 'mailing',
    title: '✉️ Mailing list',
    desc: 'Subscribers + Resend broadcast (migration 022).',
  },
];

/** Block picker labels — emoji matches default seeds in pageSections.ts */
export const PAGE_BLOCK_LABELS: Record<string, string> = {
  heading: '📌 Heading',
  text: '📝 Text',
  panel: '📦 Panel',
  callout: '💡 Callout',
  quote: '💬 Quote',
  code: '⌨️ Code',
  markdown: '📄 Markdown',
  html: '🌐 Raw HTML',
  divider: '➖ Divider',
  spacer: '↕️ Spacer',
  image: '🖼️ Image',
  video: '🎬 Video',
  gallery: '🖼️ Gallery',
  embed: '📺 Embed',
  iframe: '🪟 Iframe',
  sandbox_html: '⚡ Mini app',
  hero: '🦸 Hero',
  cta: '📣 CTA',
  buttons: '🔘 Buttons',
  download: '⬇️ Download',
  image_text: '🖼️+📝 Image + text',
  columns: '▥ Columns',
  tabs: '📑 Tabs',
  accordion: '📂 Accordion',
  faq: '❓ FAQ',
  feature_list: '✨ Features',
  stats: '📊 Stats',
  timeline: '📅 Timeline',
  pricing: '💰 Pricing',
  team: '👥 Team',
  newsletter: '✉️ Newsletter',
  game_grid: '🎮 Game grid',
  tags: '🏷️ Tags',
  comments: '💬 Comments',
};
