/* Auto-generated by scripts/inject-game-pwa.mjs — do not edit by hand. */
const CACHE_NAME = "cdd-offline-SkyBattle-096ed4246e";
const ASSETS = [
  "index.html",
  "index.js",
  "index.wasm",
  "index.pck",
  "index.png",
  "index.icon.png",
  "index.apple-touch-icon.png",
  "index.audio.worklet.js",
  "index.audio.position.worklet.js",
  "cover.png",
  "manifest.json",
  "pwa-boot.js",
  "offline-cache.json"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(ASSETS.map(async (url) => {
      if (await cache.match(url)) {
        return;
      }
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (res.ok) {
          await cache.put(url, res);
        }
      } catch (err) {
        console.warn('[cdd-offline-sw] skip', url, err);
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((key) => key.startsWith('cdd-offline-') && key !== CACHE_NAME)
        .map((key) => caches.delete(key)),
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') {
    return;
  }
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) {
    return;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    if (!req.headers.has('Range')) {
      const cached = await cache.match(req, { ignoreSearch: true });
      if (cached) {
        return cached;
      }
    }
    try {
      const res = await fetch(req);
      if (res.ok && !req.headers.has('Range')) {
        cache.put(req, res.clone());
      }
      return res;
    } catch (err) {
      const fallback = await cache.match(req, { ignoreSearch: true });
      if (fallback) {
        return fallback;
      }
      if (req.mode === 'navigate') {
        const page = await cache.match('./index.html') || await cache.match('index.html');
        if (page) {
          return page;
        }
      }
      throw err;
    }
  })());
});
